; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Trace Method Client"
#define MyAppVersion "4.6.3"
#define MyAppPublisher "ZeusSoft, Ing. Buero Bauer"
#define MyAppURL "www.zeussoft.de"
#define MyAppExeName "ZSAppTrcMthClient.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{49565956-2788-4A46-895F-C9FCF2605B64}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient
OutputBaseFilename=ZSAppTrcMthClient-Setup
SetupIconFile=C:\Projekte\ZeusSoft\ZSQtLib\main\Images\Libs\ZSSys\Zeus.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\ZSSysQt5_msvc2019_x64.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\ZSSysGUIQt5_msvc2019_x64.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\ZSIpcQt5_msvc2019_x64.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\ZSIpcGUIQt5_msvc2019_x64.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\ZSIpcTraceQt5_msvc2019_x64.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\ZSIpcTraceGUIQt5_msvc2019_x64.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\Qt5Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\Qt5Gui.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\Qt5Network.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\Qt5Svg.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\Qt5Widgets.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\Qt5Xml.dll"; DestDir: "{app}"; Flags: ignoreversion
; Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\msvcp140_1d.dll"; DestDir: "{app}"; Flags: ignoreversion
; Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\msvcp140_2d.dll"; DestDir: "{app}"; Flags: ignoreversion
; Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\msvcp140.dll"; DestDir: "{app}"; Flags: ignoreversion
; Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\msvcp140_atomic_wait.dll"; DestDir: "{app}"; Flags: ignoreversion
; Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\msvcp140_codecvt_ids.dll"; DestDir: "{app}"; Flags: ignoreversion
; Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\vccorlib140.dll"; DestDir: "{app}"; Flags: ignoreversion
; Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\vcruntime140_1d.dll"; DestDir: "{app}"; Flags: ignoreversion
; Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\vcruntime140d.dll"; DestDir: "{app}"; Flags: ignoreversion
; Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\concrt140d.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\d3dcompiler_47.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\libEGL.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\libGLESv2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\bearer\qgenericbearer.dll"; DestDir: "{app}\bearer"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\iconengines\qsvgicon.dll"; DestDir: "{app}\iconengines"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\imageformats\qgif.dll"; DestDir: "{app}\imageformats"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\imageformats\qicns.dll"; DestDir: "{app}\imageformats"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\imageformats\qico.dll"; DestDir: "{app}\imageformats"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\imageformats\qjpeg.dll"; DestDir: "{app}\imageformats"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\imageformats\qsvg.dll"; DestDir: "{app}\imageformats"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\imageformats\qtga.dll"; DestDir: "{app}\imageformats"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\imageformats\qtiff.dll"; DestDir: "{app}\imageformats"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\imageformats\qwbmp.dll"; DestDir: "{app}\imageformats"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\imageformats\qwebp.dll"; DestDir: "{app}\imageformats"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\platforms\qwindows.dll"; DestDir: "{app}\platforms"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\styles\qwindowsvistastyle.dll"; DestDir: "{app}\styles"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\translations\qt_ar.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\translations\qt_bg.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\translations\qt_ca.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\translations\qt_cs.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\translations\qt_da.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\translations\qt_de.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\translations\qt_en.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\translations\qt_es.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\translations\qt_fi.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\translations\qt_fr.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\translations\qt_gd.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\translations\qt_he.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\translations\qt_hu.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\translations\qt_it.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\translations\qt_ja.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\translations\qt_ko.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\translations\qt_lv.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\translations\qt_pl.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\translations\qt_ru.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\translations\qt_sk.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\translations\qt_tr.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\translations\qt_uk.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\Projekte\ZeusSoft\ZSQtLib\main\Dist\msvc2019_x64\Release\ZSAppTrcMthClient\translations\qt_zh_TW.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

